# Generated by Django 5.1.6 on 2025-03-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
        ('store', '0002_review_created_at_review_updated_at_review_user_and_more'),
    ]

    operations = [
    ]
