# Generated by Django 5.1.6 on 2025-04-12 12:00



from django.db import migrations, models
import datetime
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_review_created_at_remove_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
    ]
