# Generated by Django 5.0.7 on 2025-03-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bilingCountry',
            new_name='billingCountry',
        ),
    ]
